name: 🐛 Bug Report
description: Report a bug
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: textarea
    id: desc
    attributes:
      label: Description
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
  - type: dropdown
    id: priority
    attributes:
      label: 🔥 Priority
      description: Select the priority level
      options:
        - Triage
        - Critical
        - High
        - Medium
        - Low
        - Backlog
    validations:
      required: true
