name: ✨ Feature Request
description: Suggest a feature
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: textarea
    id: idea
    attributes:
      label: Idea
    validations:
      required: true
