name: 📋 Task
description: General task
title: "[Task]: "
labels: ["task", "triage"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
    validations:
      required: true
